### ISSUE TITLE
Artifact composition created multiple nodes per Artifact

### ISSUE THREAD

**Issue by arcanefoam** [jku-isse/ecco#14]
In the EMF plugin an Artifact can be referenced by many artifacts and hence can appear multiple times in the tree. 
I think the problem is that the LazyCompositionNode always creates a new node for the origNodes. So probably need a cache of Artifact:Node so they are not created more than once and instead reused.

**Comment by meik99** [comment]
The emf plugin is not part of this repository as far as I am aware, therefore I will close this issue for now. Feel free to reopen it if necessary.
